### ISSUE TITLE
AttributeError: Caught AttributeError in DataLoader worker process 0.

### ISSUE THREAD

**Issue by fylyl** [zju3dv/LoFTR#161]
您好，在训练时，发生这个问题，请问您有遇到过吗，我应该如何解决，实在想不到解决方法了，麻烦了，报错信息如下：
11.6 M    Trainable params
0         Non-trainable params
11.6 M    Total params
46.246    Total estimated model params size (MB)
Validation sanity check: 0it [00:00, ?it/s]2022-03 | INFO     | src.lightning.data:val_dataloader:302 - [rank:0/1]: Val Sampler and DataLoader re-init.
Validation sanity check:   0%|                                                                  | 0/10 [00:00<?, ?it/s]Traceback (most recent call last):
  File "./train.py", line 124, in <module>
    main()
  File "./train.py", line 119, in main
    trainer.fit(model, datamodule=data_module)
  File "D:\soft\Anaconda3\envs\loftr2\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 458, in fit
    self._run(model)
  File "D:\soft\Anaconda3\envs\loftr2\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 756, in _run
    self.dispatch()
  File "D:\soft\Anaconda3\envs\loftr2\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 797, in dispatch
    self.accelerator.start_training(self)
  File "D:\soft\Anaconda3\envs\loftr2\lib\site-packages\pytorch_lightning\accelerators\accelerator.py", line 96, in start_training
    self.training_type_plugin.start_training(trainer)
  File "D:\soft\Anaconda3\envs\loftr2\lib\site-packages\pytorch_lightning\plugins\training_type\training_type_plugin.py", line 144, in start_training
    self._results = trainer.run_stage()
  File "D:\soft\Anaconda3\envs\loftr2\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 807, in run_stage
    return self.run_train()
  File "D:\soft\Anaconda3\envs\loftr2\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 842, in run_train
    self.run_sanity_check(self.lightning_module)
  File "D:\soft\Anaconda3\envs\loftr2\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1107, in run_sanity_check
    self.run_evaluation()
  File "D:\soft\Anaconda3\envs\loftr2\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 949, in run_evaluation
    for batch_idx, batch in enumerate(dataloader):
  File "D:\soft\Anaconda3\envs\loftr2\lib\site-packages\torch\utils\data\dataloader.py", line 517, in __next__
    data = self._next_data()
  File "D:\soft\Anaconda3\envs\loftr2\lib\site-packages\torch\utils\data\dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "D:\soft\Anaconda3\envs\loftr2\lib\site-packages\torch\utils\data\dataloader.py", line 1225, in _process_data
    data.reraise()
  File "D:\soft\Anaconda3\envs\loftr2\lib\site-packages\torch\_utils.py", line 429, in reraise
    raise self.exc_type(msg)
**AttributeError: Caught AttributeError in DataLoader worker process 0.**
Original Traceback (most recent call last):
  File "D:\soft\Anaconda3\envs\loftr2\lib\site-packages\torch\utils\data\_utils\worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "D:\soft\Anaconda3\envs\loftr2\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\soft\Anaconda3\envs\loftr2\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\soft\Anaconda3\envs\loftr2\lib\site-packages\torch\utils\data\dataset.py", line 219, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "D:\LoFTR-master\src\datasets\megadepth.py", line 75, in __getitem__
    image0, mask0, scale0 = read_megadepth_gray(
  File "D:\LoFTR-master\src\utils\dataset.py", line 109, in read_megadepth_gray
    w, h = image.shape[1], image.shape[0]
**AttributeError: 'NoneType' object has no attribute 'shape'**

**Comment by zehongs** [comment]
似乎是路径上没有数据

**Comment by fylyl** [comment]
非常感谢，受到您的启发，问题解决了

**Comment by chen9run** [comment]
> 非常感谢，受到您的启发，问题解决了

你好，请问是如何解决的，我也遇到了相同的问题

**Comment by chen9run** [comment]
你好，真的很需要你的帮助，十分感谢

**Comment by Luxiaowen45** [comment]
你好，我的两个报错和您是一样的。您是路径里找不到数据吗，跟本原因在于路径写错了吗？

**Comment by QiuhangLiu** [comment]
> 你好，我的两个报错和您是一样的。您是路径里找不到数据吗，跟本原因在于路径写错了吗？

您好 我也报了这个错误，请问您解决了吗？请问您的数据是怎么做的软链接呢？现在没有D2Net了会不会和这个有关系，我就直接这样子了
ln -sv /path/to/megadepth/phoenix /path/to/LoFTR/data/megadepth/train
ln -sv /path/to/megadepth/phoenix /path/to/LoFTR/data/megadepth/test

ln -s /path/to/megadepth_indices/* /path/to/LoFTR/data/megadepth/index

**Comment by Luxiaowen45** [comment]
很抱歉，时间太久没有看到。我这个报错已经解决了。我出错的原因不是路径写错，而是训练集和测试集的划分有问题：我有一个测试集的数据在csv中censorship值都为0，所以报错。
另外，我还有一个问题，就是代码csv表格中，censorship=1是不是代表此数据为删失数据？

在 2023-06-07 23:46:28，Qiuhang ***@***.***> 写道：


你好，我的两个报错和您是一样的。您是路径里找不到数据吗，跟本原因在于路径写错了吗？

您好 我也报了这个错误，请问您解决了吗？请问您的数据是怎么做的软链接呢？现在没有D2Net了会不会和这个有关系，我就直接这样子了
ln -sv /path/to/megadepth/phoenix /path/to/LoFTR/data/megadepth/train
ln -sv /path/to/megadepth/phoenix /path/to/LoFTR/data/megadepth/test

ln -s /path/to/megadepth_indices/* /path/to/LoFTR/data/megadepth/index
