### ISSUE TITLE
Data "D2-Net preprocessed images" is unavailable

### ISSUE THREAD

**Issue by WallofWonder** [zju3dv/LoFTR#265]
404 is reported. 
<img width="776" alt="屏幕截图 2023-04-25 152413" src="https://user-images.githubusercontent.com/46950043/234205054-c85e58e3-8627-486c-abbc-8463ce33baef.png">
<img width="546" alt="屏幕截图 2023-04-25 152442" src="https://user-images.githubusercontent.com/46950043/234205089-6eba971f-04a4-4de9-9d6f-884bf4c29dee.png">

**Comment by trand2k** [comment]
i have same issue

**Comment by nonathecoda** [comment]
how did you solve the issue? @trand2k  @WallofWonder

**Comment by WallofWonder** [comment]
> 

still waiting for a solution

**Comment by nonathecoda** [comment]
they actually updated the readme, in the FAQ you can read that they recommend to leave the d2net dataset away.

**Comment by QiuhangLiu** [comment]
> they actually updated the readme, in the FAQ you can read that they recommend to leave the d2net dataset away.

Do you know how to train this with only Megadepth? Like how we build the symlink then?

**Comment by nonathecoda** [comment]
what error do you get? I started training some minutes ago, but didn't get an error yet.

**Comment by QiuhangLiu** [comment]
> what error do you get? I started training some minutes ago, but didn't get an error yet.

Hi, thanks so much for replying. Did you train by Scanner or Megadepth? How did you set the training process? I used megadepth but the undistorted data from D2Net is unavailable, I downloaded the original Megadepth SfM datasets(600+GB) to replace that dataset. 

My error shows:
File "D:\soft\Anaconda3\envs\loftr2\lib\site-packages\torch\utils\data\dataloader.py", line 1225, in _process_data
data.reraise()
File "D:\soft\Anaconda3\envs\loftr2\lib\site-packages\torch_utils.py", line 429, in reraise
raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
File "D:\soft\Anaconda3\envs\loftr2\lib\site-packages\torch\utils\data_utils\worker.py", line 202, in _worker_loop
data = fetcher.fetch(index)
File "D:\soft\Anaconda3\envs\loftr2\lib\site-packages\torch\utils\data_utils\fetch.py", line 44, in fetch
data = [self.dataset[idx] for idx in possibly_batched_index]
File "D:\soft\Anaconda3\envs\loftr2\lib\site-packages\torch\utils\data_utils\fetch.py", line 44, in
data = [self.dataset[idx] for idx in possibly_batched_index]
File "D:\soft\Anaconda3\envs\loftr2\lib\site-packages\torch\utils\data\dataset.py", line 219, in getitem
return self.datasets[dataset_idx][sample_idx]
File "D:\LoFTR-master\src\datasets\megadepth.py", line 75, in getitem
image0, mask0, scale0 = read_megadepth_gray(
File "D:\LoFTR-master\src\utils\dataset.py", line 109, in read_megadepth_gray
w, h = image.shape[1], image.shape[0]
AttributeError: 'NoneType' object has no attribute 'shape'

My whole process is like this:
1. Environment settings (exactly like guidance)
2. Download Megadepth v1(200GB) and Megadepth SfM (600GB)
3. Build symlinks:(I rename the megadeath SfMdataset to “Undistorted_SfM”)
ln -sv /path/to/megadepth/phoenix /path/to/megadepth_d2net/Undistorted_SfM /path/to/LoFTR/data/megadepth/train
ln -sv /path/to/megadepth/phoenix /path/to/megadepth_d2net/Undistorted_SfM /path/to/LoFTR/data/megadepth/test
ln -s /path/to/megadepth_indices/* /path/to/LoFTR/data/megadepth/index
4. Run
bash scripts/reproduce_train/outdoor_ds.sh

Have you done any other process besides this?

Btw, May I ask what gpus did you use? I use 4 A5000 with 24GB memories each. Could the error caused by the equipments?

PS: Could you please add my WhatsApp (+65 93512175) for further contact? We could discuss some more details.

I am really appreciate your kind reply. (Got no one in lab research same topic😭)

**Comment by nonathecoda** [comment]
https://github.com/zju3dv/LoFTR/issues/276#issuecomment-1600921374

@WallofWonder @trand2k

**Comment by LinMenwill** [comment]
@nonathecoda HI, I download the megadepth from the provided [https://www.cs.cornell.edu/projects/megadepth/dataset/Megadepth_v1/MegaDepth_v1.tar.gz](url), but the folders are split by sequence :(, how to split the dataset into /train /test ?
![图片](https://github.com/zju3dv/LoFTR/assets/45513982/5ed0f8fc-7e98-48a0-8f2e-48218d21a1f6)

**Comment by jvbshsai** [comment]
> > 你遇到了什么错误？我几分钟前开始训练，但还没遇到错误。
> 
> 您好，非常感谢您的回复。请问您是用 Scanner 还是 Megadepth 进行训练的？训练过程是如何设置的？我用的是 Megadepth，但是 D2Net 的无畸变数据不可用，所以我下载了原始的 Megadepth SfM 数据集（600+GB）来替代。
> 
> 我的错误信息显示： 文件“D:\soft\Anaconda3\envs\loftr2\lib\site-packages\torch\utils\data\dataloader.py”，第 1225 行，在 _process_data 中 data.reraise() 文件“D:\soft\Anaconda3\envs\loftr2\lib\site-packages\torch_utils.py”，第 429 行，在 reraise 中 raise self.exc_type(msg) AttributeError: 在 DataLoader 工作进程 0 中捕获到 AttributeError。 原始回溯（最近一次调用）： 文件“D:\soft\Anaconda3\envs\loftr2\lib\site-packages\torch\utils\data_utils\worker.py”，第 202 行，在 _worker_loop 中 data = fetcher.fetch(index) 文件“D:\soft\Anaconda3\envs\loftr2\lib\site-packages\torch\utils\data_utils\fetch.py​​”，第 44 行，在 fetch 中 data = [self.dataset[idx] for idx in possible_batched_index] 文件“D:\soft\Anaconda3\envs\loftr2\lib\site-packages\torch\utils\data_utils\fetch.py​​”，第 44 行，在 data = [self.dataset[idx] for idx in possible_batched_index] 文件“D:\soft\Anaconda3\envs\loftr2\lib\site-packages\torch\utils\data\dataset.py”，第 219 行，在 getitem 中 return self.datasets[dataset_idx][sample_idx] 文件“D:\LoFTR-master\src\datasets\megadepth.py”，第 75 行，在 getitem 中 image0, mask0, scale0 = read_megadepth_gray( 文件“D:\LoFTR-master\src\utils\dataset.py”，第 109 行，在read_megadepth_gray w, h = image.shape[1], image.shape[0] AttributeError: 'NoneType' 对象没有属性 'shape'
> 
> 我的整个流程是这样的：
> 
> 1. 环境设置（与指导完全相同）
> 2. 下载 Megadepth v1（200GB）和 Megadepth SfM（600GB）
> 3. 构建符号链接：（我将 MegaDeath SfM 数据集重命名为“Undistorted_SfM”）
>    ln -sv /path/to/megadepth/phoenix /path/to/megadepth_d2net/Undistorted_SfM /path/to/LoFTR/data/megadepth/train 
>    ln -sv /path/to/megadepth/phoenix /path/to/megadepth_d2net/Undistorted_SfM /path/to/LoFTR/data/megadepth/test 
>    ln -s /path/to/megadepth_indices/* /path/to/LoFTR/data/megadepth/index
> 4. 运行
>    bash 脚本/reproduce_train/outdoor_ds.sh
> 
> 除了这个步骤之外，你还进行过其他操作吗？
> 
> 顺便问一下，你用的是什么显卡？我用的是4块A5000，每块都有24GB显存。会不会是设备的问题？
> 
> PS：能否请您添加我的WhatsApp（+65 93512175）以便进一步联系？我们可以讨论更多细节。
> 
> 非常感谢您的回复。（实验室里没有人研究过这个课题😭）

您好 请问您后续如何解决的呢
