### ISSUE TITLE
RuntimeError: main thread is not in main loop

### ISSUE THREAD

**Issue by chen9run** [zju3dv/LoFTR#266]

**Comment by minzhy** [comment]
Hi,I encouter the same problem. How did you solve this problem.

**Comment by AlmogHagag** [comment]
Same problem:

Exception ignored in: <function Variable.__del__ at 0x7f11818e8b80>
Traceback (most recent call last):
  File "/home/micromamba/envs/loftrWin/lib/python3.8/tkinter/__init__.py", line 363, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x7f11818e8b80>
Traceback (most recent call last):
  File "/home/micromamba/envs/loftrWin/lib/python3.8/tkinter/__init__.py", line 363, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
**RuntimeError: main thread is not in main loop**

**Comment by minzhy** [comment]
您好，您的邮件我已收到，我会尽快查看并给您回复。谢谢

**Comment by 447425299** [comment]
Hi,I encouter the same problem. How did you solve this problem.

**Comment by minzhy** [comment]
您好，您的邮件我已收到，我会尽快查看并给您回复。谢谢

**Comment by 447425299** [comment]
Exception ignored in: <function Image.__del__ at 0x7fea3fca8940>
Traceback (most recent call last):
  File "/home/lsp/anaconda3/envs/loftr/lib/python3.8/tkinter/__init__.py", line 4017, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
