### ISSUE TITLE
meet an error when training loftr: EOFError: Ran out of input

### ISSUE THREAD

**Issue by RunyuZhu** [zju3dv/LoFTR#298]
**when i run the outdoor_ds.sh file, an error occurred.
when "loading train datasets" reach at 14%(51/368), sys will report an error called EOFError
the details will list below:**
{'accelerator': 'ddp',
 'accumulate_grad_batches': 1,
 'amp_backend': 'native',
 'amp_level': 'O2',
 'auto_lr_find': False,
 'auto_scale_batch_size': False,
 'auto_select_gpus': False,
 'batch_size': 1,
 'benchmark': True,
 'check_val_every_n_epoch': 1,
 'checkpoint_callback': True,
 'ckpt_path': None,
 'data_cfg_path': 'configs/data/megadepth_trainval_640.py',
 'default_root_dir': None,
 'deterministic': False,
 'disable_ckpt': False,
 'distributed_backend': None,
 'exp_name': 'outdoor-ds-640-bs=1',
 'fast_dev_run': False,
 'flush_logs_every_n_steps': 1,
 'gpus': 1,
 'gradient_clip_algorithm': 'norm',
 'gradient_clip_val': 0.0,
 'limit_predict_batches': 1.0,
 'limit_test_batches': 1.0,
 'limit_train_batches': 1.0,
 'limit_val_batches': 1.0,
 'log_every_n_steps': 1,
 'log_gpu_memory': None,
 'logger': True,
 'main_cfg_path': 'configs/loftr/outdoor/loftr_ds_dense.py',
 'max_epochs': 30,
 'max_steps': None,
 'max_time': None,
 'min_epochs': None,
 'min_steps': None,
 'move_metrics_to_cpu': False,
 'multiple_trainloader_mode': 'max_size_cycle',
 'num_nodes': 1,
 'num_processes': 1,
 'num_sanity_val_steps': 10,
 'num_workers': 4,
 'overfit_batches': 0.0,
 'parallel_load_data': False,
 'pin_memory': True,
 'plugins': None,
 'precision': 32,
 'prepare_data_per_node': True,
 'process_position': 0,
 'profiler': None,
 'profiler_name': None,
 'progress_bar_refresh_rate': None,
 'reload_dataloaders_every_epoch': False,
 'replace_sampler_ddp': True,
 'resume_from_checkpoint': None,
 'stochastic_weight_avg': False,
 'sync_batchnorm': False,
 'terminate_on_nan': False,
 'tpu_cores': None,
 'track_grad_norm': -1,
 'truncated_bptt_steps': None,
 'val_check_interval': 1.0,
 'weights_save_path': None,
 'weights_summary': 'top'}
Global seed set to 66
2024-01-08 19:56:17.127 | INFO     | __main__:main:82 - LoFTR LightningModule initialized!
2024-01-08 19:56:17.127 | INFO     | __main__:main:86 - LoFTR DataModule initialized!
Missing logger folder: logs/tb_logs/outdoor-ds-640-bs=1
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
2024-01-08 19:56:17.145 | INFO     | __main__:main:117 - Trainer initialized!
2024-01-08 19:56:17.146 | INFO     | __main__:main:118 - Start training!
Global seed set to 66
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/1
2024-01-08 19:56:17.760 | INFO     | src.lightning.data:setup:118 - [rank:0] world_size: 1
2024-01-08 19:56:17.760 | INFO     | src.lightning.data:_setup_dataset:184 - [rank 0]: 368 scene(s) assigned.
[rank:0] loading train datasets:  14%|███████████████████████▌                                                                                                                                                  | 51/368 [00:02<00:18, 17.58it/s]
Traceback (most recent call last):
  File "./train.py", line 123, in <module>
    main()
  File "./train.py", line 119, in main
    trainer.fit(model, datamodule=data_module)
  File "/home/gzz/miniconda3/envs/loftr/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 458, in fit
    self._run(model)
  File "/home/gzz/miniconda3/envs/loftr/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 713, in _run
    self.call_setup_hook(model)  # allow user to setup lightning_module in accelerator environment
  File "/home/gzz/miniconda3/envs/loftr/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1159, in call_setup_hook
    self.datamodule.setup(stage=fn)
  File "/home/gzz/miniconda3/envs/loftr/lib/python3.8/site-packages/pytorch_lightning/core/datamodule.py", line 385, in wrapped_fn
    return fn(*args, **kwargs)
  File "/home/gzz/zhu/LoFTR/src/lightning/data.py", line 125, in setup
    self.train_dataset = self._setup_dataset(
  File "/home/gzz/zhu/LoFTR/src/lightning/data.py", line 189, in _setup_dataset
    return dataset_builder(data_root, local_npz_names, split_npz_root, intri_path,
  File "/home/gzz/zhu/LoFTR/src/lightning/data.py", line 223, in _build_concat_dataset
    MegaDepthDataset(data_root,
  File "/home/gzz/zhu/LoFTR/src/datasets/megadepth.py", line 48, in __init__
    self.scene_info = dict(np.load(npz_path, allow_pickle=True))
  File "/home/gzz/miniconda3/envs/loftr/lib/python3.8/site-packages/numpy/lib/npyio.py", line 253, in __getitem__
    return format.read_array(bytes,
  File "/home/gzz/miniconda3/envs/loftr/lib/python3.8/site-packages/numpy/lib/format.py", line 792, in read_array
    array = pickle.load(fp, **pickle_kwargs)
EOFError: Ran out of input

**does any one ever meet the similar issue
I'd appreciate it if you could offer some advice
thanks
zhu**

**Comment by RunyuZhu** [comment]
#276 
i retry follow this issue, the problem seems solved.
but, before the first EOFError occur, im sure i have run the code given by Mr nonathecode in #276 
now, i run it again, EOFError may get solved

**Comment by panjiadipanjiadi** [comment]
> #276 i retry follow this issue, the problem seems solved. but, before the first EOFError occur, im sure i have run the code given by Mr nonathecode in #276 now, i run it again, EOFError may get solved

您好，请问最后你用一个gpu训练成功了吗，我也想这么尝试

**Comment by panjiadipanjiadi** [comment]
> #276 i retry follow this issue, the problem seems solved. but, before the first EOFError occur, im sure i have run the code given by Mr nonathecode in #276 now, i run it again, EOFError may get solved

Hello, did you successfully train with a gpu in the end? I also want to try this
