### ISSUE TITLE
can you provide data structure for training?

### ISSUE THREAD

**Issue by Xuanyuanbingxue** [zju3dv/LoFTR#60]
Hi, thank you so much for your great work! When I tried to train the model on my computer, I got some errors like this:
`Traceback (most recent call last):
  File "/home/xzliu/LoFTR-master/train.py", line 123, in <module>
    main()
  File "/home/xzliu/LoFTR-master/train.py", line 119, in main
    trainer.fit(model, datamodule=data_module)
  File "/home/xzliu/anaconda3/envs/loftr/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 553, in fit
    self._run(model)
  File "/home/xzliu/anaconda3/envs/loftr/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 918, in _run
    self._dispatch()
  File "/home/xzliu/anaconda3/envs/loftr/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 986, in _dispatch
    self.accelerator.start_training(self)
  File "/home/xzliu/anaconda3/envs/loftr/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 92, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/home/xzliu/anaconda3/envs/loftr/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 161, in start_training
    self._results = trainer.run_stage()
  File "/home/xzliu/anaconda3/envs/loftr/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 996, in run_stage
    return self._run_train()
  File "/home/xzliu/anaconda3/envs/loftr/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1031, in _run_train
    self._run_sanity_check(self.lightning_module)
  File "/home/xzliu/anaconda3/envs/loftr/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1115, in _run_sanity_check
    self._evaluation_loop.run()
  File "/home/xzliu/anaconda3/envs/loftr/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/home/xzliu/anaconda3/envs/loftr/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 110, in advance
    dl_outputs = self.epoch_loop.run(
  File "/home/xzliu/anaconda3/envs/loftr/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/home/xzliu/anaconda3/envs/loftr/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 93, in advance
    batch_idx, batch = next(dataloader_iter)
  File "/home/xzliu/anaconda3/envs/loftr/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/xzliu/anaconda3/envs/loftr/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 557, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/xzliu/anaconda3/envs/loftr/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/xzliu/anaconda3/envs/loftr/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/xzliu/anaconda3/envs/loftr/lib/python3.8/site-packages/torch/utils/data/dataset.py", line 219, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/home/xzliu/LoFTR-master/src/datasets/scannet.py", line 78, in __getitem__
    image0 = read_scannet_gray(img_name0, resize=(640, 480), augment_fn=None)
  File "/home/xzliu/LoFTR-master/src/utils/dataset.py", line 154, in read_scannet_gray
    image = cv2.resize(image, (640,480))
cv2.error: OpenCV(4.4.0) /tmp/pip-req-build-zeowd5_m/opencv/modules/imgproc/src/resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'resize'

`
I tried to search the errors on the Internet, the answer told me that maybe I got the wrong position of datasets. So can you provide the detailed data structure for training datasets? Or have you ever met errors like this? Thank you and looking forward to your reply.

**Comment by tsingyig** [comment]
Hi, I'm having the same problem, can you tell me how you solved it? @Xuanyuanbingxue
